Repository UCLALibrary/ftva-website-nuxt, pull requests merged in 2024-10, with the labels that each got.

#45 fix: APPS-2966 page fix eventDescription text is truncated
  gql/queries/FTVAEventSeriesDetail.gql
  pages/series/[slug].vue
Labels: fix

#43 feat: APPS-2955 remaining components
  cypress/e2e/blogArticlePage.cy.js
  gql/queries/FTVAArticleDetail.gql
  package.json
  pages/blog/[slug].vue
  pages/events/[slug].vue
  pnpm-lock.yaml
  utils/socialList.js
Labels: feature

#46 fix: Apps-2975 implement 2col on event detail, slot event detail in new position
  pages/events/[slug].vue
Labels: bugfix

#47 fix: APPS-2970 dateTimes incorrect in ftva
  gql/queries/EventDetail.gql
  gql/queries/FTVAEventDetail.gql
  gql/queries/FTVAEventList.gql
  gql/queries/FTVAEventSeriesDetail.gql
  gql/queries/FTVAEventSeriesList.gql
Labels: bugfix

#49 fix: APPS-2998 Update inline carousels with new prop
  package.json
  pages/events/[slug].vue
  pages/series/[slug].vue
  pnpm-lock.yaml
Labels: fix

#50 chore: APPS-3000 Update FTVA Globals Query
  server/api/fetchNitroStorageCraftGlobalData.js
Labels: chore

#48 feat: Apps-2996 add collection route and gql
  assets/styles/listing-pages.scss
  gql/queries/FTVACollectionDetail.gql
  gql/queries/FTVACollectionList.gql
  pages/blog/index.vue
  pages/collections/[slug].vue
  pages/collections/index.vue
  pages/events/index.vue
Labels: feature

#51 feat: APPS-2997 finish collection detail page
  cypress/e2e/collectionDetailPage.cy.js
  package.json
  pages/blog/[slug].vue
  pages/collections/[slug].vue
  pages/collections/index.vue
  pages/series/[slug].vue
  pnpm-lock.yaml
Labels: feature

#53 chore: APPS-2974 add title of entry as value for <title> tag in template
  nuxt.config.ts
  pages/blog/[slug].vue
  pages/collections/[slug].vue
  pages/events/[slug].vue
  pages/series/[slug].vue
Labels: chore

#54 fix: APPS-3009 Increase heapsize for production build
  composables/useHeader.js
  modules/init.js
  package.json
  pages/collections/[slug].vue
  pages/events/[slug].vue
  pages/series/[slug].vue
  plugins/craft-layout-data.client.js
  plugins/data-api.js
  plugins/indexer.server.js
  utils/arrayOfArrays.js
Labels: fix

#55 chore: Disable all console statements
  app.vue
  layouts/default.vue
  modules/init.js
  nuxt.config.ts
  plugins/data-api.js
Labels: chore

#56 fix: APPS-2968 EventSeriesDetail - Sort past events by DESC order
  gql/queries/FTVAEventSeriesDetail.gql
Labels: fix

#58 fix: APPS-2965 Update series page breadcrumb parent title
  pages/series/[slug].vue
Labels: fix

#60 feat: delete old es index when making new
  modules/finalize.js
  modules/init.js
Labels: feature

#63 fix: APPS-3039 update sidebar col breakpoint
  package.json
  pages/events/[slug].vue
  pages/series/[slug].vue
  pnpm-lock.yaml
Labels: fix

#59 feat: APPS-3007 Add BlockInfo external icon
  package.json
  pages/collections/[slug].vue
  pnpm-lock.yaml
Labels: enhancement

#61 fix: APPS-2976 & APPS-3011 updates to cardMeta - BlogDetail & EventDetail pages
  gql/queries/FTVAEventDetail.gql
  nuxt.config.ts
  package.json
  pages/blog/[slug].vue
  pages/events/[slug].vue
  pnpm-lock.yaml
Labels: fix

#65 feat: APPS-3010 Consolidate slug page styles
  assets/styles/slug-pages.scss
  pages/blog/[slug].vue
  pages/collections/[slug].vue
  pages/events/[slug].vue
  pages/series/[slug].vue
Labels: fix
