Repository UCLALibrary/ftva-website-nuxt, pull requests merged in 2024-08, with the labels that each got.

#14 fix: APPS-2844 maxwidth, which helps fix most carousel issues
  pages/events/[slug].vue
Labels: fix

#12 fix: APPS-2849
  .github/workflows/ci.yml
  .github/workflows/percy.yml
  .github/workflows/production-site-build.yml
  .github/workflows/regenerate-site.yml
  nuxt.config.ts
  package.json
Labels: bugfix

#15 chore: APPS-2866 Update FTVA Nuxt with library component version 3.5.7
  .github/workflows/production-site-build.yml
  .github/workflows/regenerate-site.yml
  nuxt.config.ts
  package.json
  pages/events/[slug].vue
  pnpm-lock.yaml
Labels: chore

#18 chore: APPS-2883 update section-title in on the EventDetail page in the SectionTeaserCard
  pages/events/[slug].vue
Labels: chore

#17 fix: APPS-2874 Page SectionTeaserCard Link
  gql/queries/FTVAEventDetail.gql
Labels: bug, fix

#20 fix: APPS-2869 Remove fixed height on embedded video sizer
  pages/events/[slug].vue
Labels: fix

#24 chore: Update library components to version 3.6.4
  package.json
  pages/events/[slug].vue
  pnpm-lock.yaml
Labels: chore

#25 fix: APPS-2878 Show Only Upcoming Events in a Series
  gql/queries/FTVAEventDetail.gql
  pages/events/[slug].vue
Labels: fix

#26 fix: APPS-2884 Temporarily disable image query
  gql/queries/FTVAEventList.gql
  gql/queries/FTVAEventSeriesList.gql
Labels: fix

#19 fix: APPS-2870 Page TextDescription and GuestSpeakerre-arranged to fix text truncation problem
  cypress/e2e/eventDetailPage.cy.js
  cypress/e2e/homepage.cy.js
  gql/queries/FTVAEventDetail.gql
  pages/events/[slug].vue
Labels: fix

#21 fix: set aspect ratio for images
  pages/events/[slug].vue
Labels: fix

#30 fix: APPS-2893 set max height blue box for large screens
  pages/events/[slug].vue
Labels: bug, fix

#28 feat: APPS-2757 Assemble default layout with footer variations
  app.vue
  cypress/e2e/homepage.cy.js
  gql/queries/FTVAFooterLinks.gql
  gql/queries/FTVAFooterPrimaryItems.gql
  gql/queries/FTVAFooterSockItems.gql
  layouts/default.vue
  package.json
  plugins/init.server.js
  pnpm-lock.yaml
  server/api/fetchNitroStorageCraftFooterLinksData.js
  server/api/fetchNitroStorageCraftFooterPrimaryData.js
  server/api/fetchNitroStorageCraftFooterSockData.js
  server/api/fetchNitroStorageCraftFooterSponsorData.js
  stores/GlobalStore.js
Labels: feature

#29 chore: APPS-2864 Write E2E tests for EventDetail Page template
  .github/workflows/ci.yml
  cypress/e2e/eventDetailPage.cy.js
  cypress/support/commands.ts
  layouts/default.vue
  pages/events/[slug].vue
  pages/events/index.vue
  pages/series/index.vue
  pnpm-lock.yaml
Labels: chore
