Repository UCLALibrary/ftva-website-nuxt, pull requests merged in 2024-12, with the labels that each got.

#73 feat: APPS-3075 Add calendar component to the calendar view and pass ES events data
  nuxt.config.ts
  package.json
  pages/events/index.vue
  plugins/vuetify.ts
  pnpm-lock.yaml
Labels: feature

#74 feat: APPS-3085 APPS-3086 update and refactor ES code for different views and Date filter
  composables/useCalendarSearchFilter.js
  composables/useDateFilterQuery.js
  composables/useListSearchFilter.js
  pages/events/index.vue
Labels: feature

#75 feat: APPS-3052 Update ftvaEventSeries query
  gql/queries/FTVAEventSeriesList.gql
  package.json
  pages/series/index.vue
  pnpm-lock.yaml
Labels: feature

#80 chore: APPS-3088 add vuetify components for Calendar
  plugins/vuetify.ts
Labels: chore

#82 feat: APPS-3076 Add typescript and SectionRemoveSearchFilters
  composables/useContentIndexer.js
  composables/useListSearchFilter.js
  modules/finalize.js
  modules/init.js
  package.json
  pages/events/index.vue
  pnpm-lock.yaml
Labels: feature

#81 feat: APPS-3050 Add a new gql query on the page for title, summary
  gql/queries/FTVAEventList.gql
  pages/events/index.vue
Labels: feature

#84 feat: Add vue use infinitescroll composable for mobile screens
  pages/events/index.vue
  utils/getEventFilterLabels.js
Labels: feature

#76 feat: APPS-3078 add highlight logic for filters
  package.json
  pages/events/index.vue
  pnpm-lock.yaml
  utils/getEventFilterLabels.js
Labels: feature

#85 feat: APPS-3059 Add ES search Query with pagination to filter by past, current and upcoming series
  composables/useEventSeriesListSearchFilter.js
  cypress/e2e/eventSeriesListPage.cy.js
  package.json
  pages/series/index.vue
Labels: feature

#88 fix: increase node memory size
  package.json
Labels: fix

#89 feat: APPS-3111 Add infinite scrolling for mobile screens for series listing page
  gql/queries/FTVAEventSeriesDetail.gql
  pages/events/index.vue
  pages/series/index.vue
Labels: feature

#90 feat: APPS-3114 Add ongoing to the current and ongoing query on eventSeries page
  composables/useEventSeriesListSearchFilter.js
Labels: feature

#87 feat: APPS-3051 Update Event Index Styling
  cypress/e2e/eventListPage.cy.js
  package.json
  pages/events/index.vue
  pnpm-lock.yaml
Labels: enhancement
