Repository UCLALibrary/ftva-website-nuxt, pull requests merged in 2024-07, with the labels that each got.

#3 feat: APPS-2742 Create basic template for Event detail page with query
  .env.example
  cypress/e2e/homepage.cy.js
  gql/queries/EventDetail.gql
  gql/queries/EventWorkshopList.gql
  gql/queries/FTVAEventDetail.gql
  gql/queries/FTVAEventDetailSeries.gql
  gql/queries/FTVAEventList.gql
  gql/queries/FTVAEventSeriesList.gql
  nuxt.config.ts
  package.json
  pages/events/[slug].vue
  pages/events/index.vue
  pages/series/index.vue
  pnpm-lock.yaml
Labels: feature

#4 fix: example
  .env.example
Labels: fix

#5 fix: ci for production build
  .github/workflows/production-site-build.yml
Labels: fix, ci

#7 fix: yaml syntax
  .github/workflows/production-site-build.yml
Labels: bugfix

#8 fix: Add imports and fix uri, as we have added trailing slash to the urls now in component library
  pages/events/index.vue
Labels: bugfix

#6 feat: APPS-2743 Assemble the EventDetail page
  app.vue
  composables/provideTheme.js
  cypress/e2e/eventDetailPage.cy.js
  cypress/e2e/homepage.cy.js
  gql/queries/FTVAEventDetail.gql
  layouts/default.vue
  package.json
  pages/events/[slug].vue
  pages/series/index.vue
  plugins/init.server.js
  pnpm-lock.yaml
Labels: feature

#9 fix: Page BlockInfo & EventSeries issues
  gql/queries/FTVAEventDetail.gql
  pages/events/[slug].vue
Labels: fix

#11 fix: APPS-2854 Page ftvaEvent query to title: eventTitle
  gql/queries/FTVAEventDetail.gql
Labels: fix

#13 fix: APPS-2855 Page Adjust the width of Sidebar
  pages/events/[slug].vue
Labels: fix

#10 fix: APPS-2842 grid layout causing space at top of layout
  .gitignore
  pages/events/[slug].vue
Labels: fix
