Repository UCLALibrary/ftva-website-nuxt, pull requests merged in 2024-09, with the labels that each got.

#34 feat: APPS-2891 add header to page layout
  layouts/default.vue
  package.json
  pages/events/[slug].vue
  pnpm-lock.yaml
Labels: feature

#35 fix: Upcoming Events card responsiveness, max-width work and background color FTVA variation in SectionWrapper
  package.json
  pages/events/[slug].vue
  pnpm-lock.yaml
Labels: fix

#37 fix: APPS-2921 Update SeriesDetail query
  gql/queries/FTVAEventSeriesDetail.gql
Labels: fix

#38 fix: APPS 2927 Update Header query
  package.json
  pnpm-lock.yaml
  server/api/fetchNitroStorageCraftHeaderData.js
Labels: fix

#36 feat: APPS-2928 prerendering error pages and draft previews layout
  app.vue
  composables/useHeader.js
  error.vue
  gql/queries/FTVAFooterLinks.gql
  gql/queries/FTVAFooterPrimaryItems.gql
  gql/queries/FTVAFooterSockItems.gql
  gql/queries/FTVALayout.gql
  gql/queries/HeaderMainMenuItems.gql
  layouts/default.vue
  pages/events/[slug].vue
  pages/index.vue
  plugins/craft-layout-data.client.js
Labels: feature, bugfix

#39 feat: APPS-2910 assemble event series page
  assets/styles/global.scss
  cypress/e2e/eventSeriesDetailPage.cy.js
  gql/queries/FTVAEventSeriesDetail.gql
  package.json
  pages/events/[slug].vue
  pages/series/[slug].vue
  pages/series/index.vue
  pnpm-lock.yaml
Labels: feature

#42 fix: APPS-2949 Multiple Event Series page fixes
  package.json
  pages/series/[slug].vue
  pnpm-lock.yaml
Labels: fix
