Repository UCLALibrary/ftva-website-nuxt, pull requests merged in 2024-11, with the labels that each got.

#64 feat: APPS-3024 es query for tags
  composables/useIndexAggregator.js
  pages/events/index.vue
Labels: enhancement, feature

#67 feat: APPS-3023 Create composable useContentIndexer to index craft data used on all routes for FTVA
  composables/useContentIndexer.js
  gql/queries/FTVAArticleDetail.gql
  gql/queries/FTVACollectionDetail.gql
  gql/queries/FTVAEventDetail.gql
  gql/queries/FTVAEventSeriesDetail.gql
  pages/blog/[slug].vue
  pages/collections/[slug].vue
  pages/events/[slug].vue
  pages/series/[slug].vue
Labels: feature

#68 fix: APPS-3054 Update Queries, Composable, Logic for Event filters
  composables/useIndexAggregator.js
  gql/queries/FTVAEventDetail.gql
  gql/queries/FTVAEventSeriesDetail.gql
  package.json
  pages/events/[slug].vue
  pages/events/index.vue
  pages/series/[slug].vue
  pnpm-lock.yaml
Labels: fix

#69 fix: APPS-3065 Refactor TagLabels Parsing Logic
  pages/events/[slug].vue
  pages/series/[slug].vue
  utils/getEventFilterLabels.js
Labels: fix

#70 fix: Add routes and use import.meta
  app.vue
  error.vue
  layouts/default.vue
  modules/init.js
  nuxt.config.ts
  plugins/indexer.server.js
Labels: fix

#71 feat: Add datefilter and section pagination
  assets/styles/listing-pages.scss
  assets/styles/slug-pages.scss
  composables/useSearchFilter.js
  pages/events/index.vue
  utils/getEventFilterLabels.js
Labels: feature, draft
