Repository UCLALibrary/ftva-website-nuxt, pull requests merged in 2025-05, with the labels that each got.

#146 feat: APPS-3293 Assemble Collection Listing Type page
  composables/useCollectionListSearch.js
  cypress/e2e/collectionListingPage.cy.js
  gql/queries/FTVACollectionDetail.gql
  package.json
  pages/collections/motion-picture/index.vue
  pnpm-lock.yaml
Labels: feature

#150 feat: Add useRoute and update component version to add the fix for alphabetical browseby
  package.json
  pages/collections/la-rebellion/filmmakers/index.vue
  pnpm-lock.yaml
Labels: bugfix

#144 feat: APPS-3299 assemble complex collections page
  components/ListOfItemsCollection.vue
  composables/useListSearchFilter.js
  cypress/e2e/collectionDetailPage.cy.js
  gql/queries/FTVACollectionItem.gql
  gql/queries/FTVACollectionType.gql
  pages/collections/[collectionSlug]/[slug].vue
  pages/collections/[slug].vue
Labels: feature

#151 fix: APPS-3324 Restore VideoEmbed element after Craft fix
  pages/collections/[collectionSlug]/[slug].vue
Labels: fix

#153 fix: render basicCollections without infoblock text data
  components/BasicCollection.vue
Labels: bugfix

#154 feat: Replace wildcard search with prefix query and add a new field to remove article from title and use it for Alphabetical browse
  components/BasicCollection.vue
  components/ListOfItemsCollection.vue
  composables/useCollectionListSearch.js
  gql/queries/FTVACollectionType.gql
  modules/init.js
  pages/collections/[collectionSlug]/[slug].vue
  pages/collections/motion-picture/index.vue
  utils/normalizeTitleForAlphabeticalBrowseBy.ts
Labels: feature

#155 feat: APPS-3315 Create Storytelling template GraphQL
  components/StorytellingCollection.vue
  cypress/e2e/collectionItemDetailPage.cy.js
  gql/fragments/BlockCardWithImageFragment.gql
  gql/queries/FTVACollectionStory.gql
  pages/collections/[slug].vue
  pages/collections/la-rebellion/index.vue
Labels: feature

#156 feat: Apps-3310 infinite scroll composable
  composables/useMobileOnlyInfiniteScroll.js
  pages/blog/index.vue
Labels: feature

#164 fix: event series listing styles
  pages/series/index.vue
Labels: bugfix
