Repository UCLALibrary/ftva-website-nuxt, pull requests merged in 2025-03, with the labels that each got.

#116 feat: APPS-3231 Refactor BlockInfo on slug pages
  assets/styles/slug-pages.scss
  package.json
  pages/events/[slug].vue
  pages/series/[slug].vue
  pnpm-lock.yaml
Labels: enhancement

#115 feat: APPS-3230 update the allftva fpb query to include card with image
  app.vue
  error.vue
  gql/fragments/BlockCardWithImageFragment.gql
  gql/fragments/collections/AllFtvaFpb.gql
  layouts/default.vue
  nuxt.config.ts
  package.json
  pages/[...slug].vue
  pages/blog/[slug].vue
  pages/blog/index.vue
  pages/collections/[collectionSlug]/[slug].vue
  pages/collections/[slug].vue
  pages/collections/index.vue
  pages/collections/la-rebellion/filmmakers/[slug].vue
  pages/collections/la-rebellion/filmmakers/index.vue
  pages/events/[slug].vue
  pages/events/index.vue
  pages/series/[slug].vue
  pages/series/index.vue
  plugins/add-library-website-vue-components.js
  pnpm-lock.yaml
Labels: feature

#121 feat: APPS-3244 new route and GQL
  gql/queries/FTVAEntryARSCIMCS.gql
  nuxt.config.ts
  pages/archive-research-study-center/index.vue
  pages/billy-wilder-theater/index.vue
Labels: feature

#120 feat: APPS-3151 Assemble the General Content page with components
  assets/styles/slug-pages.scss
  composables/useContentIndexer.js
  gql/fragments/BlockCardWithImageFragment.gql
  gql/queries/EventDetail.gql
  gql/queries/ExhibitionsAndEventsList.gql
  gql/queries/ExhibitionsAndEventsListSingle.gql
  package.json
  pages/[...slug].vue
  pages/[...slug].vue.bak
  pages/blog/[slug].vue
  pages/collections/[slug].vue
  pages/collections/la-rebellion/filmmakers/[slug].vue
  pages/events/[slug].vue
  pages/series/[slug].vue
  plugins/data-api.js
  plugins/indexer.server.js
  pnpm-lock.yaml
Labels: feature

#122 feat: APPS-3240 Assemble Billy Wilder page
  cypress/e2e/billyWilderTheater.cy.js
  gql/queries/BillyWilderTheater.gql
  pages/billy-wilder-theater/index.vue
Labels: feature

#123 feat: use component librray nuxt module with auto imports, remove auto imports and disable crawler, add all the routes to routes array in nuxt.config
  app.vue
  composables/useContentIndexer.js
  error.vue
  layouts/default.vue
  nuxt.config.ts
  package.json
  pages/[...slug].vue
  pages/archive-research-study-center/index.vue
  pages/billy-wilder-theater/index.vue
  pages/blog/[slug].vue
  pages/blog/index.vue
  pages/collections/[collectionSlug]/[slug].vue
  pages/collections/[slug].vue
  pages/collections/index.vue
  pages/collections/la-rebellion/filmmakers/[slug].vue
  pages/collections/la-rebellion/filmmakers/index.vue
  pages/events/[slug].vue
  pages/events/index.vue
  pages/series/[slug].vue
  pages/series/index.vue
  plugins/add-vue-skip-to.js
  pnpm-lock.yaml
Labels: feature

#124 fix: APPS-3248 Add spacing between Flexible Blocks
  pages/[...slug].vue
Labels: fix

#126 feat: remove duplicate styles
  nuxt.config.ts
Labels: feature

#125 fix: APPS-3259 Fix PageAnchor on GeneralContent page
  assets/styles/slug-pages.scss
  cypress/e2e/eventDetailPage.cy.js
  nuxt.config.ts
  package.json
  pages/[...slug].vue
  pages/collections/la-rebellion/filmmakers/[slug].vue
  pages/events/[slug].vue
  pnpm-lock.yaml
Labels: fix

#128 fix: APPS-3218 change table header for film to title
  pages/collections/la-rebellion/filmmakers/[slug].vue
Labels: bugfix

#127 feat: APPS-3246 finish assembling arsc & IMCS page
  assets/styles/slug-pages.scss
  cypress/e2e/archiveResearchStudyCenter.js
  pages/archive-research-study-center/index.vue
Labels: feature

#129 fix: remove x from share options
  utils/socialList.js
Labels: bugfix
