Repository UCLALibrary/ftva-website-nuxt, pull requests merged in 2025-09, with the labels that each got.

#200 fix: APPS-3402 motion-picture collection page will not load from search results link
  pages/archive-research-study-center/index.vue
  pages/collections/la-rebellion/filmography/index.vue
  pages/collections/motion-picture/index.vue
Labels: bugfix

#197 feat: APPS-3389 fix error screen on 'archive-research-study-center' route
  components/ListOfItemsCollection.vue
  nuxt.config.ts
  pages/[...slug].vue
  pages/archive-research-study-center.vue
  pages/billy-wilder-theater.vue
  pages/collections/la-rebellion/filmmakers/[slug].vue
  pages/collections/la-rebellion/filmography/index.vue
  pages/collections/la-rebellion/index.vue
  pages/events/[slug].vue
  pages/search.vue
  pages/series/[slug].vue
Labels: feature

#211 fix: APPS-3434 update search results no results text
  pages/search.vue
Labels: fix

#209 feat: APPS-3435 add 2 new sort options to filmmakers page
  pages/collections/la-rebellion/filmmakers/index.vue
Labels: feature

#213 feat: APPS-3430 use titleSort for sitesearch
  components/BasicCollection.vue
  components/ListOfItemsCollection.vue
  gql/queries/FTVALARebellionFilmmakersDetail.gql
  gql/queries/StaffListwithfulldetail.gql.example
  modules/init.js
  pages/[...slug].vue
  pages/archive-research-study-center.vue
  pages/billy-wilder-theater.vue
  pages/blog/[slug].vue
  pages/blog/index.vue
  pages/collections/[collectionSlug]/[slug].vue
  pages/collections/index.vue
  pages/collections/la-rebellion/filmmakers/[slug].vue
  pages/collections/la-rebellion/filmmakers/index.vue
  pages/collections/la-rebellion/index.vue
  pages/collections/motion-picture/index.vue
  pages/events/[slug].vue
  pages/events/index.vue
  pages/index.vue
  pages/search.vue
  pages/series/[slug].vue
  pages/series/index.vue
  utils/normalizeTitleForAlphabeticalBrowseBy.ts
Labels: feature

#212 fix: APPS-3449 In The Life episodes data fetching
  components/ListOfItemsCollection.vue
Labels: fix

#217 fix: APPS-3448 expect infoblock array, add heading
  components/BasicCollection.vue
  gql/queries/FTVACollectionDetail.gql
Labels: bugfix

#216 fix: update components library in package.json
  package.json
  pnpm-lock.yaml
Labels: fix

#201 fix: APPS-3416 Update Breadcrumb instances for title overrides
  assets/styles/listing-pages.scss
  assets/styles/slug-pages.scss
  components/ListOfItemsCollection.vue
  package.json
  pages/[...slug].vue
  pages/collections/[collectionSlug]/[slug].vue
  pages/collections/la-rebellion/filmmakers/[slug].vue
  pages/collections/la-rebellion/filmmakers/index.vue
  pages/collections/la-rebellion/filmography/index.vue
  pages/search.vue
  pages/series/[slug].vue
  pnpm-lock.yaml
  utils/parseBreadcrumbTitles.js
Labels: fix

#219 fix: APPS-3443 heading showing without content
  pages/collections/la-rebellion/index.vue
Labels: bugfix

#220 fix: APPS-3454 remove country from info block on ASRC and IMCS pages
  pages/archive-research-study-center.vue
Labels: bugfix
