Repository UCLALibrary/ftva-website-nuxt, pull requests merged in 2025-08, with the labels that each got.

#190 chore: APPS-3283 remove collection group
  pages/collections/[collectionSlug]/[slug].vue
Labels: chore

#186 fix: APPS-3212 pagination skipping on last page on desktop
  components/ListOfItemsCollection.vue
  composables/usePaginationScroll.ts
  error.vue
  pages/blog/index.vue
  pages/collections/motion-picture/index.vue
  pages/search.vue
  pages/series/index.vue
Labels: bug, fix

#192 feat: update component and design token package
  package.json
  pnpm-lock.yaml
Labels: feature

#193 feat: APPS-3180 add display summary logic
  gql/queries/FTVACollectionTypeListing.gql
  gql/queries/FTVAEventSeriesList.gql
  pages/archive-research-study-center/index.vue
  pages/blog/index.vue
  pages/collections/la-rebellion/filmmakers/index.vue
  pages/collections/motion-picture/index.vue
  pages/series/index.vue
Labels: feature

#191 feat: Refactor pagination scroll with useScroll from VueUse package
  .github/workflows/percy.yml
  .github/workflows/setup-workspace/action.yml
  components/ListOfItemsCollection.vue
  composables/usePaginationScroll.ts
  package.json
  pages/archive-research-study-center/index.vue
  pages/blog/index.vue
  pages/collections/la-rebellion/filmmakers/index.vue
  pages/collections/motion-picture/index.vue
  pages/events/index.vue
  pages/search.vue
  pages/series/index.vue
  pnpm-lock.yaml
Labels: feature

#195 fix: APPS-3397 Pull url data for homepage carousel
  package.json
  pages/index.vue
  pnpm-lock.yaml
Labels: fix

#199 fix: APPS 3411 Update page pagination
  components/ListOfItemsCollection.vue
  package.json
  pages/blog/index.vue
  pages/collections/la-rebellion/filmmakers/index.vue
  pages/collections/motion-picture/index.vue
  pages/search.vue
  pages/series/index.vue
  pnpm-lock.yaml
Labels: fix
