Repository UCLALibrary/ftva-website-nuxt, pull requests merged in 2025-02, with the labels that each got.

#106 fix: APPS-3164 fix craft for general content epic flexible page block
  gql/fragments/BlockTextColumnsFragment.gql
  gql/fragments/collections/AllFtvaFpb.gql
Labels: fix

#104 fix: APPS-3160 Update BlockCardWithImage on the article listing page
  package.json
  pages/blog/index.vue
  pnpm-lock.yaml
Labels: fix

#110 feat: APPS 3141 Add Collection Item Detail query
  error.vue
  gql/queries/FTVACollectionItem.gql
  pages/collections/[collectionSlug]/[slug].vue
Labels: feature

#111 chore: APPS-3162 Replace SectionStaffSubjectLibrarian component with new TableComponent
  package.json
  pages/collections/la-rebellion/filmmakers/[slug].vue
  pnpm-lock.yaml
Labels: chore

#113 fix: update allFtvaFpb query to get rid of the associatedCards Flexible Block
  gql/fragments/collections/AllFtvaFpb.gql
  nuxt.config.ts
Labels: fix
