Repository UCLALibrary/ftva-website-nuxt, pull requests merged in 2025-10, with the labels that each got.

#225 feat: APPS-3472 swap title for eventTitle in now showing section
  pages/index.vue
Labels: feature

#218 fix: APPS-3424 Fix Footer Spacing
  assets/styles/general-pages.scss
  assets/styles/global.scss
  components/BasicCollection.vue
  components/ListOfItemsCollection.vue
  pages/[...slug].vue
  pages/archive-research-study-center.vue
  pages/billy-wilder-theater.vue
  pages/blog/index.vue
  pages/collections/[collectionSlug]/[slug].vue
  pages/collections/[slug].vue
  pages/collections/index.vue
  pages/collections/la-rebellion/filmmakers/[slug].vue
  pages/collections/la-rebellion/filmmakers/index.vue
  pages/collections/la-rebellion/index.vue
  pages/collections/motion-picture/index.vue
  pages/events/[slug].vue
  pages/events/index.vue
  pages/index.vue
  pages/search.vue
  pages/series/index.vue
Labels: fix

#226 fix: sort order for ongoing titles
  gql/queries/FTVAEventSeriesList.gql
  pages/series/index.vue
Labels: bugfix

#224 feat: APPS-3442 Update h3,h4, h5 tags fpb richtext
  package.json
  pages/[...slug].vue
  pages/archive-research-study-center.vue
  pages/blog/[slug].vue
  pages/collections/la-rebellion/index.vue
  pnpm-lock.yaml
Labels: feature
