Repository UCLALibrary/ftva-website-nuxt, pull requests merged in 2025-04, with the labels that each got.

#132 fix: set max height for featured articles in blog listing page
  pages/blog/index.vue
Labels: bug, fix

#130 fix: change section title for section in collection item page
  pages/collections/[collectionSlug]/[slug].vue
Labels: bug, fix

#131 fix: APPS 3265 Update Vuetify config in FTVA Nuxt
  package.json
  plugins/vuetify.ts
  pnpm-lock.yaml
Labels: fix

#136 fix: APPS-3200 section-header color on events listing
  pages/events/index.vue
Labels: bugfix

#138 fix: APPS-3209 image sizing on cards in blog listing page
  pages/blog/index.vue
Labels: bugfix

#135 feat: APPS-3290 Add CollectionsListingType GQL
  gql/queries/FTVACollectionTypeListing.gql
  nuxt.config.ts
  pages/collections/motion-picture/index.vue
Labels: feature

#141 fix: Font properties for day in blockCardThreeColumn in Events Listing
  pages/events/index.vue
Labels: bugfix

#142 fix: APPS-3303 Add gridLayout prop to SectionTeaserCards
  package.json
  pages/blog/[slug].vue
  pages/collections/[collectionSlug]/[slug].vue
  pages/collections/[slug].vue
  pages/events/[slug].vue
  pages/series/[slug].vue
  pnpm-lock.yaml
Labels: fix

#139 feat: APPS-3273 finish General content page
  cypress/e2e/generalContent.cy.js
  gql/fragments/BlockCardWithImageFragment.gql
  package.json
  pages/[...slug].vue
  plugins/vuetify.ts
  pnpm-lock.yaml
Labels: feature

#137 feat: APPS-3295 APPS-3296 add collectionlayout query, split collections/[slug].vue layout in 3 components
  components/BasicCollection.vue
  components/ListOfItemsCollection.vue
  components/StorytellingCollection.vue
  gql/queries/FTVACollectionType.gql
  pages/collections/[slug].vue
Labels: feature

#143 feat: APPS-3301 Add CollectionListing composable
  composables/useCollectionListSearch.js
  gql/queries/FTVACollectionTypeListing.gql
  pages/collections/motion-picture/index.vue
Labels: feature

#145 feat: Add aggregation query for ListOfItemsCollection single select dropdown component
  components/ListOfItemsCollection.vue
  composables/useCollectionAggregator.js
  gql/queries/FTVACollectionType.gql
  pages/collections/[collectionSlug]/[slug].vue
  pages/collections/[slug].vue
  pages/collections/la-rebellion/filmmakers/[slug].vue
  pages/collections/la-rebellion/filmmakers/index.vue
  pages/collections/motion-picture/index.vue
  utils/searchConfig.js
Labels: feature
